name: 'Autotest Agent'
description: 'Automated testing agent with Android emulator setup and AI-powered test execution'

inputs:
  openai_api_base:
    description: 'OpenAI API base URL'
    required: true
  openai_api_key:
    description: 'OpenAI API key'
    required: true
  testrail_url:
    description: 'TestRail URL'
    required: true
  testrail_email:
    description: 'TestRail email'
    required: true
  testrail_api_key:
    description: 'TestRail API key'
    required: true
  suite_id:
    description: 'TestRail suite ID'
    required: true
  jf_url:
    description: 'JFrog URL'
    required: true
  jf_access_token:
    description: 'JFrog access token'
    required: true
  apk_path:
    description: 'Path to the APK file in JFrog'
    required: true


outputs:
  test_results:
    description: 'Test execution results'
    value: 'Test execution completed'

runs:
  using: 'composite'
  
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Agent dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
    
    - uses: jfrog/setup-jfrog-cli@v2
    - name: Configure JFrog CLI
      shell: bash
      run: |
        jf config add my-server \
          --url ${{ inputs.jf_url }} \
          --access-token ${{ inputs.jf_access_token }} \
          --interactive=false

    - name: Download APK via JFrog CLI
      shell: bash
      run: |
          jf rt dl ${{ inputs.apk_path }} app.apk --flat=true

    - name: Run Autotest Agent
      uses: Consumer-MagicMountain/android-emulator-runner@main
      with:
        api-level: 29
        arch: arm64-v8a
        target: google_apis
        script: |
          adb install app.apk
          adb shell am start -n com.trendmicro.fraudbuster/com.trendmicro.callblock.activity.SplashActivity
          robot -d NONE -o NONE -r NONE -l NONE setup_app.robot

          cd ${{ github.action_path }}
          python3 main.py
      env:
        OPENAI_API_BASE: ${{ inputs.openai_api_base }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        TESTRAIL_URL: ${{ inputs.testrail_url }}
        TESTRAIL_EMAIL: ${{ inputs.testrail_email }}
        TESTRAIL_API_KEY: ${{ inputs.testrail_api_key }}
        SUITE_ID: ${{ inputs.suite_id }}