name: Run Autotest Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  autotest:
    # runs-on: self-hosted
    runs-on: ebf-vm-macos-arm-14@${{ github.run_id }}-test
    environment: AutoTest-Agent

    steps:
      - name: Run CI by Autotest Agent
        uses: Consumer-MagicMountain/AutoTest-Agent@main
        with:
          jf_url: ${{ secrets.JF_URL }}
          jf_access_token: ${{ secrets.JF_ACCESS_TOKEN }}
          openai_api_base: ${{ secrets.OPENAI_API_BASE }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          testrail_url: ${{ secrets.TESTRAIL_URL }}
          testrail_email: ${{ secrets.TESTRAIL_EMAIL }}
          testrail_api_key: ${{ secrets.TESTRAIL_API_KEY }}
          apk_path: 'tmcchk-android-generic-prod-local/2.0.2173/beta_en_debug_2.0.2173.apk'
          suite_id: '457904'
